dataset:
  val: m4_weekly
  test: traffic
  weighted: 0

gpt:
  max_epochs: 10000
  context_length: 1024
  n_layer: 8
  n_embd_per_head: 16
  n_head: 4
  scaling: std
  lr: 0.001
  weight_decay: 0.00000001
  aug_prob: 0.5
  aug_rate: 0.1
  num_parallel_samples: 100
  batch_size: 1
  batches_per_epoch: 100
CUDA:
  device_id: 0